package fr.mom.arkeo.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-04-07T07:59:18.048+02:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://soap.arkeo.mom.fr/", name = "ArkManager")
@XmlSeeAlso({ObjectFactory.class})
public interface ArkManager {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getArk", targetNamespace = "http://soap.arkeo.mom.fr/", className = "fr.mom.arkeo.soap.GetArk")
    @WebMethod
    @ResponseWrapper(localName = "getArkResponse", targetNamespace = "http://soap.arkeo.mom.fr/", className = "fr.mom.arkeo.soap.GetArkResponse")
    public fr.mom.arkeo.soap.Ark getArk(
        @WebParam(name = "arg0", targetNamespace = "")
        fr.mom.arkeo.soap.Account arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createArk", targetNamespace = "http://soap.arkeo.mom.fr/", className = "fr.mom.arkeo.soap.CreateArk")
    @WebMethod
    @ResponseWrapper(localName = "createArkResponse", targetNamespace = "http://soap.arkeo.mom.fr/", className = "fr.mom.arkeo.soap.CreateArkResponse")
    public fr.mom.arkeo.soap.Ark createArk(
        @WebParam(name = "arg0", targetNamespace = "")
        fr.mom.arkeo.soap.Account arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        fr.mom.arkeo.soap.Ark arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateArk", targetNamespace = "http://soap.arkeo.mom.fr/", className = "fr.mom.arkeo.soap.UpdateArk")
    @WebMethod
    @ResponseWrapper(localName = "updateArkResponse", targetNamespace = "http://soap.arkeo.mom.fr/", className = "fr.mom.arkeo.soap.UpdateArkResponse")
    public fr.mom.arkeo.soap.Ark updateArk(
        @WebParam(name = "arg0", targetNamespace = "")
        fr.mom.arkeo.soap.Account arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        fr.mom.arkeo.soap.Ark arg1
    );
}
