
package fr.mom.arkeo.soap;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2014-09-12T12:03:33.853+02:00
 * Generated source version: 3.0.0-milestone2
 * 
 */
public final class ArkManager_ArkManagerPort_Client {

    private static final QName SERVICE_NAME = new QName("http://soap.arkeo.mom.fr/", "ArkManagerService");

    private ArkManager_ArkManagerPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ArkManagerService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ArkManagerService ss = new ArkManagerService(wsdlURL, SERVICE_NAME);
        ArkManager port = ss.getArkManagerPort();  
        
        {
        System.out.println("Invoking createArk...");
        fr.mom.arkeo.soap.Account _createArk_arg0 = new fr.mom.arkeo.soap.Account();
        _createArk_arg0.setBaseId("BaseId659651404");
        java.util.List<fr.mom.arkeo.soap.Group> _createArk_arg0Groups = new java.util.ArrayList<fr.mom.arkeo.soap.Group>();
        fr.mom.arkeo.soap.Group _createArk_arg0GroupsVal1 = new fr.mom.arkeo.soap.Group();
        _createArk_arg0GroupsVal1.setId("Id1496684911");
        _createArk_arg0GroupsVal1.setName("Name-87851629");
        _createArk_arg0Groups.add(_createArk_arg0GroupsVal1);
        _createArk_arg0.getGroups().addAll(_createArk_arg0Groups);
        fr.mom.arkeo.soap.User _createArk_arg0User = new fr.mom.arkeo.soap.User();
        _createArk_arg0User.setDbId(-875362012);
        _createArk_arg0User.setFirstname("Firstname831395132");
        _createArk_arg0User.setLastname("Lastname-1527618713");
        _createArk_arg0User.setMail("Mail273011875");
        _createArk_arg0User.setUid("Uid1384450556");
        _createArk_arg0User.setUser("User-123685299");
        fr.mom.arkeo.soap.Group _createArk_arg0UserUserGroup = new fr.mom.arkeo.soap.Group();
        _createArk_arg0UserUserGroup.setId("Id-1876723655");
        _createArk_arg0UserUserGroup.setName("Name-615009618");
        _createArk_arg0User.setUserGroup(_createArk_arg0UserUserGroup);
        _createArk_arg0.setUser(_createArk_arg0User);
        fr.mom.arkeo.soap.Ark _createArk_arg1 = new fr.mom.arkeo.soap.Ark();
        _createArk_arg1.setArk("Ark186566895");
        _createArk_arg1.setCreator("Creator-310207084");
        _createArk_arg1.setDate("Date859293869");
        java.util.List<fr.mom.arkeo.soap.DcElement> _createArk_arg1DcElements = new java.util.ArrayList<fr.mom.arkeo.soap.DcElement>();
        fr.mom.arkeo.soap.DcElement _createArk_arg1DcElementsVal1 = new fr.mom.arkeo.soap.DcElement();
        _createArk_arg1DcElementsVal1.setLanguage("Language675829042");
        _createArk_arg1DcElementsVal1.setName("Name-644334540");
        _createArk_arg1DcElementsVal1.setValue("Value1035231974");
        _createArk_arg1DcElements.add(_createArk_arg1DcElementsVal1);
        _createArk_arg1.getDcElements().addAll(_createArk_arg1DcElements);
        _createArk_arg1.setDescription("Description-1864565752");
        _createArk_arg1.setLanguage("Language1824116274");
        _createArk_arg1.setLinkup(false);
        _createArk_arg1.setNaan("Naan1175788666");
        _createArk_arg1.setName("Name-1298411802");
        fr.mom.arkeo.soap.User _createArk_arg1Owner = new fr.mom.arkeo.soap.User();
        _createArk_arg1Owner.setDbId(-1227367294);
        _createArk_arg1Owner.setFirstname("Firstname-117781738");
        _createArk_arg1Owner.setLastname("Lastname-1101808948");
        _createArk_arg1Owner.setMail("Mail1859849036");
        _createArk_arg1Owner.setUid("Uid-1309834176");
        _createArk_arg1Owner.setUser("User500918210");
        fr.mom.arkeo.soap.Group _createArk_arg1OwnerUserGroup = new fr.mom.arkeo.soap.Group();
        _createArk_arg1OwnerUserGroup.setId("Id1941946051");
        _createArk_arg1OwnerUserGroup.setName("Name-1735299587");
        _createArk_arg1Owner.setUserGroup(_createArk_arg1OwnerUserGroup);
        _createArk_arg1.setOwner(_createArk_arg1Owner);
        _createArk_arg1.setQualifier("Qualifier178072485");
        _createArk_arg1.setRedirect(true);
        _createArk_arg1.setSaved(false);
        _createArk_arg1.setSubject("Subject-1533014772");
        _createArk_arg1.setTitle("Title-151568387");
        _createArk_arg1.setType("Type-467815116");
        _createArk_arg1.setUrlTarget("UrlTarget418245098");
        fr.mom.arkeo.soap.Ark _createArk__return = port.createArk(_createArk_arg0, _createArk_arg1);
        System.out.println("createArk.result=" + _createArk__return);


        }
        {
        System.out.println("Invoking updateArk...");
        fr.mom.arkeo.soap.Account _updateArk_arg0 = new fr.mom.arkeo.soap.Account();
        _updateArk_arg0.setBaseId("BaseId-1638657102");
        java.util.List<fr.mom.arkeo.soap.Group> _updateArk_arg0Groups = new java.util.ArrayList<fr.mom.arkeo.soap.Group>();
        fr.mom.arkeo.soap.Group _updateArk_arg0GroupsVal1 = new fr.mom.arkeo.soap.Group();
        _updateArk_arg0GroupsVal1.setId("Id-538466573");
        _updateArk_arg0GroupsVal1.setName("Name483142240");
        _updateArk_arg0Groups.add(_updateArk_arg0GroupsVal1);
        _updateArk_arg0.getGroups().addAll(_updateArk_arg0Groups);
        fr.mom.arkeo.soap.User _updateArk_arg0User = new fr.mom.arkeo.soap.User();
        _updateArk_arg0User.setDbId(-920204353);
        _updateArk_arg0User.setFirstname("Firstname1562896225");
        _updateArk_arg0User.setLastname("Lastname1379041298");
        _updateArk_arg0User.setMail("Mail-1821603170");
        _updateArk_arg0User.setUid("Uid1577397389");
        _updateArk_arg0User.setUser("User1858669081");
        fr.mom.arkeo.soap.Group _updateArk_arg0UserUserGroup = new fr.mom.arkeo.soap.Group();
        _updateArk_arg0UserUserGroup.setId("Id1773992584");
        _updateArk_arg0UserUserGroup.setName("Name-234053394");
        _updateArk_arg0User.setUserGroup(_updateArk_arg0UserUserGroup);
        _updateArk_arg0.setUser(_updateArk_arg0User);
        fr.mom.arkeo.soap.Ark _updateArk_arg1 = new fr.mom.arkeo.soap.Ark();
        _updateArk_arg1.setArk("Ark1337637418");
        _updateArk_arg1.setCreator("Creator-1024897543");
        _updateArk_arg1.setDate("Date-764984532");
        java.util.List<fr.mom.arkeo.soap.DcElement> _updateArk_arg1DcElements = new java.util.ArrayList<fr.mom.arkeo.soap.DcElement>();
        fr.mom.arkeo.soap.DcElement _updateArk_arg1DcElementsVal1 = new fr.mom.arkeo.soap.DcElement();
        _updateArk_arg1DcElementsVal1.setLanguage("Language-1357356427");
        _updateArk_arg1DcElementsVal1.setName("Name1584119534");
        _updateArk_arg1DcElementsVal1.setValue("Value1605840408");
        _updateArk_arg1DcElements.add(_updateArk_arg1DcElementsVal1);
        _updateArk_arg1.getDcElements().addAll(_updateArk_arg1DcElements);
        _updateArk_arg1.setDescription("Description2055786177");
        _updateArk_arg1.setLanguage("Language632202608");
        _updateArk_arg1.setLinkup(false);
        _updateArk_arg1.setNaan("Naan-683515755");
        _updateArk_arg1.setName("Name-328170372");
        fr.mom.arkeo.soap.User _updateArk_arg1Owner = new fr.mom.arkeo.soap.User();
        _updateArk_arg1Owner.setDbId(-2129276058);
        _updateArk_arg1Owner.setFirstname("Firstname1387172723");
        _updateArk_arg1Owner.setLastname("Lastname-858851860");
        _updateArk_arg1Owner.setMail("Mail2053016771");
        _updateArk_arg1Owner.setUid("Uid2056063645");
        _updateArk_arg1Owner.setUser("User1315232436");
        fr.mom.arkeo.soap.Group _updateArk_arg1OwnerUserGroup = new fr.mom.arkeo.soap.Group();
        _updateArk_arg1OwnerUserGroup.setId("Id376084875");
        _updateArk_arg1OwnerUserGroup.setName("Name-2088384457");
        _updateArk_arg1Owner.setUserGroup(_updateArk_arg1OwnerUserGroup);
        _updateArk_arg1.setOwner(_updateArk_arg1Owner);
        _updateArk_arg1.setQualifier("Qualifier998859470");
        _updateArk_arg1.setRedirect(true);
        _updateArk_arg1.setSaved(false);
        _updateArk_arg1.setSubject("Subject-453037324");
        _updateArk_arg1.setTitle("Title-1690941157");
        _updateArk_arg1.setType("Type-1921193208");
        _updateArk_arg1.setUrlTarget("UrlTarget-716960700");
        fr.mom.arkeo.soap.Ark _updateArk__return = port.updateArk(_updateArk_arg0, _updateArk_arg1);
        System.out.println("updateArk.result=" + _updateArk__return);


        }

        System.exit(0);
    }

}
