
package fr.mom.arkeo.soap;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-04-07T07:59:17.996+02:00
 * Generated source version: 3.1.6
 * 
 */
public final class ArkManager_ArkManagerPort_Client {

    private static final QName SERVICE_NAME = new QName("http://soap.arkeo.mom.fr/", "ArkManagerService");

    private ArkManager_ArkManagerPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ArkManagerService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ArkManagerService ss = new ArkManagerService(wsdlURL, SERVICE_NAME);
        ArkManager port = ss.getArkManagerPort();  
        
        {
        System.out.println("Invoking getArk...");
        fr.mom.arkeo.soap.Account _getArk_arg0 = new fr.mom.arkeo.soap.Account();
        _getArk_arg0.setBaseId("BaseId920379871");
        java.util.List<fr.mom.arkeo.soap.Group> _getArk_arg0Groups = new java.util.ArrayList<fr.mom.arkeo.soap.Group>();
        fr.mom.arkeo.soap.Group _getArk_arg0GroupsVal1 = new fr.mom.arkeo.soap.Group();
        _getArk_arg0GroupsVal1.setId("Id-22079683");
        _getArk_arg0GroupsVal1.setName("Name-510114946");
        _getArk_arg0Groups.add(_getArk_arg0GroupsVal1);
        _getArk_arg0.getGroups().addAll(_getArk_arg0Groups);
        fr.mom.arkeo.soap.User _getArk_arg0User = new fr.mom.arkeo.soap.User();
        _getArk_arg0User.setDbId(-1758592061);
        _getArk_arg0User.setFirstname("Firstname-649071916");
        _getArk_arg0User.setLastname("Lastname-475364772");
        _getArk_arg0User.setMail("Mail567393761");
        _getArk_arg0User.setUid("Uid1623196797");
        _getArk_arg0User.setUser("User-1835985741");
        fr.mom.arkeo.soap.Group _getArk_arg0UserUserGroup = new fr.mom.arkeo.soap.Group();
        _getArk_arg0UserUserGroup.setId("Id1118359538");
        _getArk_arg0UserUserGroup.setName("Name96331275");
        _getArk_arg0User.setUserGroup(_getArk_arg0UserUserGroup);
        _getArk_arg0.setUser(_getArk_arg0User);
        java.lang.String _getArk_arg1 = "_getArk_arg1471023401";
        fr.mom.arkeo.soap.Ark _getArk__return = port.getArk(_getArk_arg0, _getArk_arg1);
        System.out.println("getArk.result=" + _getArk__return);


        }
        {
        System.out.println("Invoking createArk...");
        fr.mom.arkeo.soap.Account _createArk_arg0 = new fr.mom.arkeo.soap.Account();
        _createArk_arg0.setBaseId("BaseId-901212277");
        java.util.List<fr.mom.arkeo.soap.Group> _createArk_arg0Groups = new java.util.ArrayList<fr.mom.arkeo.soap.Group>();
        fr.mom.arkeo.soap.Group _createArk_arg0GroupsVal1 = new fr.mom.arkeo.soap.Group();
        _createArk_arg0GroupsVal1.setId("Id1418186949");
        _createArk_arg0GroupsVal1.setName("Name1764795160");
        _createArk_arg0Groups.add(_createArk_arg0GroupsVal1);
        _createArk_arg0.getGroups().addAll(_createArk_arg0Groups);
        fr.mom.arkeo.soap.User _createArk_arg0User = new fr.mom.arkeo.soap.User();
        _createArk_arg0User.setDbId(-315780325);
        _createArk_arg0User.setFirstname("Firstname-448471217");
        _createArk_arg0User.setLastname("Lastname-256319670");
        _createArk_arg0User.setMail("Mail1636953922");
        _createArk_arg0User.setUid("Uid-1599000313");
        _createArk_arg0User.setUser("User522671577");
        fr.mom.arkeo.soap.Group _createArk_arg0UserUserGroup = new fr.mom.arkeo.soap.Group();
        _createArk_arg0UserUserGroup.setId("Id393249625");
        _createArk_arg0UserUserGroup.setName("Name-483769466");
        _createArk_arg0User.setUserGroup(_createArk_arg0UserUserGroup);
        _createArk_arg0.setUser(_createArk_arg0User);
        fr.mom.arkeo.soap.Ark _createArk_arg1 = new fr.mom.arkeo.soap.Ark();
        _createArk_arg1.setArk("Ark692832214");
        _createArk_arg1.setCreator("Creator7403825");
        _createArk_arg1.setDate("Date-1686102749");
        java.util.List<fr.mom.arkeo.soap.DcElement> _createArk_arg1DcElements = new java.util.ArrayList<fr.mom.arkeo.soap.DcElement>();
        fr.mom.arkeo.soap.DcElement _createArk_arg1DcElementsVal1 = new fr.mom.arkeo.soap.DcElement();
        _createArk_arg1DcElementsVal1.setLanguage("Language-749233786");
        _createArk_arg1DcElementsVal1.setName("Name1982540477");
        _createArk_arg1DcElementsVal1.setValue("Value-304936434");
        _createArk_arg1DcElements.add(_createArk_arg1DcElementsVal1);
        _createArk_arg1.getDcElements().addAll(_createArk_arg1DcElements);
        _createArk_arg1.setDescription("Description-30749853");
        _createArk_arg1.setLanguage("Language955656113");
        _createArk_arg1.setLinkup(true);
        _createArk_arg1.setNaan("Naan-134373732");
        _createArk_arg1.setName("Name-962199341");
        fr.mom.arkeo.soap.User _createArk_arg1Owner = new fr.mom.arkeo.soap.User();
        _createArk_arg1Owner.setDbId(1666595744);
        _createArk_arg1Owner.setFirstname("Firstname1729522755");
        _createArk_arg1Owner.setLastname("Lastname-1501684353");
        _createArk_arg1Owner.setMail("Mail-1526104863");
        _createArk_arg1Owner.setUid("Uid-1043671357");
        _createArk_arg1Owner.setUser("User-923767061");
        fr.mom.arkeo.soap.Group _createArk_arg1OwnerUserGroup = new fr.mom.arkeo.soap.Group();
        _createArk_arg1OwnerUserGroup.setId("Id14411031");
        _createArk_arg1OwnerUserGroup.setName("Name1014602658");
        _createArk_arg1Owner.setUserGroup(_createArk_arg1OwnerUserGroup);
        _createArk_arg1.setOwner(_createArk_arg1Owner);
        _createArk_arg1.setQualifier("Qualifier1215492412");
        java.util.List<fr.mom.arkeo.soap.ArkQualifier> _createArk_arg1Qualifiers = new java.util.ArrayList<fr.mom.arkeo.soap.ArkQualifier>();
        fr.mom.arkeo.soap.ArkQualifier _createArk_arg1QualifiersVal1 = new fr.mom.arkeo.soap.ArkQualifier();
        _createArk_arg1QualifiersVal1.setQualifier("Qualifier273277602");
        _createArk_arg1QualifiersVal1.setUrlTarget("UrlTarget658612997");
        _createArk_arg1Qualifiers.add(_createArk_arg1QualifiersVal1);
        _createArk_arg1.getQualifiers().addAll(_createArk_arg1Qualifiers);
        _createArk_arg1.setRedirect(false);
        _createArk_arg1.setSaved(false);
        _createArk_arg1.setSubject("Subject1375180534");
        _createArk_arg1.setTitle("Title-1276764178");
        _createArk_arg1.setType("Type-943234227");
        _createArk_arg1.setUrlTarget("UrlTarget-903425174");
        _createArk_arg1.setUserArkId(1668757110);
        fr.mom.arkeo.soap.Ark _createArk__return = port.createArk(_createArk_arg0, _createArk_arg1);
        System.out.println("createArk.result=" + _createArk__return);


        }
        {
        System.out.println("Invoking updateArk...");
        fr.mom.arkeo.soap.Account _updateArk_arg0 = new fr.mom.arkeo.soap.Account();
        _updateArk_arg0.setBaseId("BaseId944735102");
        java.util.List<fr.mom.arkeo.soap.Group> _updateArk_arg0Groups = new java.util.ArrayList<fr.mom.arkeo.soap.Group>();
        fr.mom.arkeo.soap.Group _updateArk_arg0GroupsVal1 = new fr.mom.arkeo.soap.Group();
        _updateArk_arg0GroupsVal1.setId("Id2044016825");
        _updateArk_arg0GroupsVal1.setName("Name-1235263879");
        _updateArk_arg0Groups.add(_updateArk_arg0GroupsVal1);
        _updateArk_arg0.getGroups().addAll(_updateArk_arg0Groups);
        fr.mom.arkeo.soap.User _updateArk_arg0User = new fr.mom.arkeo.soap.User();
        _updateArk_arg0User.setDbId(-2017890938);
        _updateArk_arg0User.setFirstname("Firstname297292975");
        _updateArk_arg0User.setLastname("Lastname-1246901115");
        _updateArk_arg0User.setMail("Mail-120340195");
        _updateArk_arg0User.setUid("Uid627518067");
        _updateArk_arg0User.setUser("User-1500661173");
        fr.mom.arkeo.soap.Group _updateArk_arg0UserUserGroup = new fr.mom.arkeo.soap.Group();
        _updateArk_arg0UserUserGroup.setId("Id1054957333");
        _updateArk_arg0UserUserGroup.setName("Name-1808907482");
        _updateArk_arg0User.setUserGroup(_updateArk_arg0UserUserGroup);
        _updateArk_arg0.setUser(_updateArk_arg0User);
        fr.mom.arkeo.soap.Ark _updateArk_arg1 = new fr.mom.arkeo.soap.Ark();
        _updateArk_arg1.setArk("Ark-474854713");
        _updateArk_arg1.setCreator("Creator-932003921");
        _updateArk_arg1.setDate("Date1920644462");
        java.util.List<fr.mom.arkeo.soap.DcElement> _updateArk_arg1DcElements = new java.util.ArrayList<fr.mom.arkeo.soap.DcElement>();
        fr.mom.arkeo.soap.DcElement _updateArk_arg1DcElementsVal1 = new fr.mom.arkeo.soap.DcElement();
        _updateArk_arg1DcElementsVal1.setLanguage("Language-1816545361");
        _updateArk_arg1DcElementsVal1.setName("Name-621590051");
        _updateArk_arg1DcElementsVal1.setValue("Value1521263057");
        _updateArk_arg1DcElements.add(_updateArk_arg1DcElementsVal1);
        _updateArk_arg1.getDcElements().addAll(_updateArk_arg1DcElements);
        _updateArk_arg1.setDescription("Description-402818073");
        _updateArk_arg1.setLanguage("Language978271178");
        _updateArk_arg1.setLinkup(false);
        _updateArk_arg1.setNaan("Naan-1466406781");
        _updateArk_arg1.setName("Name735813665");
        fr.mom.arkeo.soap.User _updateArk_arg1Owner = new fr.mom.arkeo.soap.User();
        _updateArk_arg1Owner.setDbId(1510914907);
        _updateArk_arg1Owner.setFirstname("Firstname555149070");
        _updateArk_arg1Owner.setLastname("Lastname-1156952072");
        _updateArk_arg1Owner.setMail("Mail-1886267853");
        _updateArk_arg1Owner.setUid("Uid1948278852");
        _updateArk_arg1Owner.setUser("User-1631971926");
        fr.mom.arkeo.soap.Group _updateArk_arg1OwnerUserGroup = new fr.mom.arkeo.soap.Group();
        _updateArk_arg1OwnerUserGroup.setId("Id-360987001");
        _updateArk_arg1OwnerUserGroup.setName("Name-1578451670");
        _updateArk_arg1Owner.setUserGroup(_updateArk_arg1OwnerUserGroup);
        _updateArk_arg1.setOwner(_updateArk_arg1Owner);
        _updateArk_arg1.setQualifier("Qualifier1929072578");
        java.util.List<fr.mom.arkeo.soap.ArkQualifier> _updateArk_arg1Qualifiers = new java.util.ArrayList<fr.mom.arkeo.soap.ArkQualifier>();
        fr.mom.arkeo.soap.ArkQualifier _updateArk_arg1QualifiersVal1 = new fr.mom.arkeo.soap.ArkQualifier();
        _updateArk_arg1QualifiersVal1.setQualifier("Qualifier-575575564");
        _updateArk_arg1QualifiersVal1.setUrlTarget("UrlTarget1593115311");
        _updateArk_arg1Qualifiers.add(_updateArk_arg1QualifiersVal1);
        _updateArk_arg1.getQualifiers().addAll(_updateArk_arg1Qualifiers);
        _updateArk_arg1.setRedirect(false);
        _updateArk_arg1.setSaved(false);
        _updateArk_arg1.setSubject("Subject-1133587768");
        _updateArk_arg1.setTitle("Title-504662694");
        _updateArk_arg1.setType("Type937608714");
        _updateArk_arg1.setUrlTarget("UrlTarget-1904377753");
        _updateArk_arg1.setUserArkId(265547408);
        fr.mom.arkeo.soap.Ark _updateArk__return = port.updateArk(_updateArk_arg0, _updateArk_arg1);
        System.out.println("updateArk.result=" + _updateArk__return);


        }

        System.exit(0);
    }

}
