package fr.mom.arkeo.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-04-07T07:59:18.054+02:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "ArkManagerService", 
                  wsdlLocation = "http://ark.mom.fr/arkeo/services/ArkManagerPort?wsdl",
                  targetNamespace = "http://soap.arkeo.mom.fr/") 
public class ArkManagerService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.arkeo.mom.fr/", "ArkManagerService");
    public final static QName ArkManagerPort = new QName("http://soap.arkeo.mom.fr/", "ArkManagerPort");
    static {
        URL url = null;
        try {
            url = new URL("http://ark.mom.fr/arkeo/services/ArkManagerPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ArkManagerService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://ark.mom.fr/arkeo/services/ArkManagerPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ArkManagerService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ArkManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ArkManagerService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ArkManagerService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ArkManagerService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ArkManagerService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ArkManager
     */
    @WebEndpoint(name = "ArkManagerPort")
    public ArkManager getArkManagerPort() {
        return super.getPort(ArkManagerPort, ArkManager.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ArkManager
     */
    @WebEndpoint(name = "ArkManagerPort")
    public ArkManager getArkManagerPort(WebServiceFeature... features) {
        return super.getPort(ArkManagerPort, ArkManager.class, features);
    }

}
