
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package fr.mom.arkeo.soap;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-04-07T07:59:18.035+02:00
 * Generated source version: 3.1.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "ArkManagerService",
                      portName = "ArkManagerPort",
                      targetNamespace = "http://soap.arkeo.mom.fr/",
                      wsdlLocation = "http://ark.mom.fr/arkeo/services/ArkManagerPort?wsdl",
                      endpointInterface = "fr.mom.arkeo.soap.ArkManager")
                      
public class ArkManagerPortImpl implements ArkManager {

    private static final Logger LOG = Logger.getLogger(ArkManagerPortImpl.class.getName());

    /* (non-Javadoc)
     * @see fr.mom.arkeo.soap.ArkManager#getArk(fr.mom.arkeo.soap.Account  arg0 ,)java.lang.String  arg1 )*
     */
    public fr.mom.arkeo.soap.Ark getArk(fr.mom.arkeo.soap.Account arg0,java.lang.String arg1) { 
        LOG.info("Executing operation getArk");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            fr.mom.arkeo.soap.Ark _return = new fr.mom.arkeo.soap.Ark();
            _return.setArk("Ark-1709269914");
            _return.setCreator("Creator-113079737");
            _return.setDate("Date-1856408346");
            java.util.List<fr.mom.arkeo.soap.DcElement> _returnDcElements = new java.util.ArrayList<fr.mom.arkeo.soap.DcElement>();
            fr.mom.arkeo.soap.DcElement _returnDcElementsVal1 = new fr.mom.arkeo.soap.DcElement();
            _returnDcElementsVal1.setLanguage("Language883421837");
            _returnDcElementsVal1.setName("Name34666848");
            _returnDcElementsVal1.setValue("Value-461133898");
            _returnDcElements.add(_returnDcElementsVal1);
            _return.getDcElements().addAll(_returnDcElements);
            _return.setDescription("Description-546014925");
            _return.setLanguage("Language1202991992");
            _return.setLinkup(true);
            _return.setNaan("Naan-1783597928");
            _return.setName("Name895368959");
            fr.mom.arkeo.soap.User _returnOwner = new fr.mom.arkeo.soap.User();
            _returnOwner.setDbId(-1144511671);
            _returnOwner.setFirstname("Firstname-1615621057");
            _returnOwner.setLastname("Lastname-646841066");
            _returnOwner.setMail("Mail358002417");
            _returnOwner.setUid("Uid-140584875");
            _returnOwner.setUser("User-1983602644");
            fr.mom.arkeo.soap.Group _returnOwnerUserGroup = new fr.mom.arkeo.soap.Group();
            _returnOwnerUserGroup.setId("Id519778932");
            _returnOwnerUserGroup.setName("Name818526669");
            _returnOwner.setUserGroup(_returnOwnerUserGroup);
            _return.setOwner(_returnOwner);
            _return.setQualifier("Qualifier-2102562402");
            java.util.List<fr.mom.arkeo.soap.ArkQualifier> _returnQualifiers = new java.util.ArrayList<fr.mom.arkeo.soap.ArkQualifier>();
            fr.mom.arkeo.soap.ArkQualifier _returnQualifiersVal1 = new fr.mom.arkeo.soap.ArkQualifier();
            _returnQualifiersVal1.setQualifier("Qualifier-1269749406");
            _returnQualifiersVal1.setUrlTarget("UrlTarget-1743038073");
            _returnQualifiers.add(_returnQualifiersVal1);
            _return.getQualifiers().addAll(_returnQualifiers);
            _return.setRedirect(false);
            _return.setSaved(true);
            _return.setSubject("Subject-1266858446");
            _return.setTitle("Title426011748");
            _return.setType("Type198515300");
            _return.setUrlTarget("UrlTarget869744389");
            _return.setUserArkId(12530297);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see fr.mom.arkeo.soap.ArkManager#createArk(fr.mom.arkeo.soap.Account  arg0 ,)fr.mom.arkeo.soap.Ark  arg1 )*
     */
    public fr.mom.arkeo.soap.Ark createArk(fr.mom.arkeo.soap.Account arg0,fr.mom.arkeo.soap.Ark arg1) { 
        LOG.info("Executing operation createArk");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            fr.mom.arkeo.soap.Ark _return = new fr.mom.arkeo.soap.Ark();
            _return.setArk("Ark-1310104743");
            _return.setCreator("Creator-253103125");
            _return.setDate("Date-705639172");
            java.util.List<fr.mom.arkeo.soap.DcElement> _returnDcElements = new java.util.ArrayList<fr.mom.arkeo.soap.DcElement>();
            fr.mom.arkeo.soap.DcElement _returnDcElementsVal1 = new fr.mom.arkeo.soap.DcElement();
            _returnDcElementsVal1.setLanguage("Language-406080475");
            _returnDcElementsVal1.setName("Name1373870369");
            _returnDcElementsVal1.setValue("Value-883615238");
            _returnDcElements.add(_returnDcElementsVal1);
            _return.getDcElements().addAll(_returnDcElements);
            _return.setDescription("Description1239713865");
            _return.setLanguage("Language1380303863");
            _return.setLinkup(true);
            _return.setNaan("Naan1780458931");
            _return.setName("Name-156871684");
            fr.mom.arkeo.soap.User _returnOwner = new fr.mom.arkeo.soap.User();
            _returnOwner.setDbId(-323387766);
            _returnOwner.setFirstname("Firstname-109703142");
            _returnOwner.setLastname("Lastname-1871653271");
            _returnOwner.setMail("Mail1411677193");
            _returnOwner.setUid("Uid1499898259");
            _returnOwner.setUser("User-59718102");
            fr.mom.arkeo.soap.Group _returnOwnerUserGroup = new fr.mom.arkeo.soap.Group();
            _returnOwnerUserGroup.setId("Id335551110");
            _returnOwnerUserGroup.setName("Name1073895008");
            _returnOwner.setUserGroup(_returnOwnerUserGroup);
            _return.setOwner(_returnOwner);
            _return.setQualifier("Qualifier-958457495");
            java.util.List<fr.mom.arkeo.soap.ArkQualifier> _returnQualifiers = new java.util.ArrayList<fr.mom.arkeo.soap.ArkQualifier>();
            fr.mom.arkeo.soap.ArkQualifier _returnQualifiersVal1 = new fr.mom.arkeo.soap.ArkQualifier();
            _returnQualifiersVal1.setQualifier("Qualifier309259249");
            _returnQualifiersVal1.setUrlTarget("UrlTarget-1222360402");
            _returnQualifiers.add(_returnQualifiersVal1);
            _return.getQualifiers().addAll(_returnQualifiers);
            _return.setRedirect(true);
            _return.setSaved(false);
            _return.setSubject("Subject-812836595");
            _return.setTitle("Title-838843612");
            _return.setType("Type335114934");
            _return.setUrlTarget("UrlTarget220644561");
            _return.setUserArkId(1643166974);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see fr.mom.arkeo.soap.ArkManager#updateArk(fr.mom.arkeo.soap.Account  arg0 ,)fr.mom.arkeo.soap.Ark  arg1 )*
     */
    public fr.mom.arkeo.soap.Ark updateArk(fr.mom.arkeo.soap.Account arg0,fr.mom.arkeo.soap.Ark arg1) { 
        LOG.info("Executing operation updateArk");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            fr.mom.arkeo.soap.Ark _return = new fr.mom.arkeo.soap.Ark();
            _return.setArk("Ark-1955584147");
            _return.setCreator("Creator484298148");
            _return.setDate("Date382576468");
            java.util.List<fr.mom.arkeo.soap.DcElement> _returnDcElements = new java.util.ArrayList<fr.mom.arkeo.soap.DcElement>();
            fr.mom.arkeo.soap.DcElement _returnDcElementsVal1 = new fr.mom.arkeo.soap.DcElement();
            _returnDcElementsVal1.setLanguage("Language-129895908");
            _returnDcElementsVal1.setName("Name660544562");
            _returnDcElementsVal1.setValue("Value-496619617");
            _returnDcElements.add(_returnDcElementsVal1);
            _return.getDcElements().addAll(_returnDcElements);
            _return.setDescription("Description441485650");
            _return.setLanguage("Language1929055178");
            _return.setLinkup(false);
            _return.setNaan("Naan-1010553760");
            _return.setName("Name-716678211");
            fr.mom.arkeo.soap.User _returnOwner = new fr.mom.arkeo.soap.User();
            _returnOwner.setDbId(1298551788);
            _returnOwner.setFirstname("Firstname700303032");
            _returnOwner.setLastname("Lastname-1479644591");
            _returnOwner.setMail("Mail1179206785");
            _returnOwner.setUid("Uid-1145721962");
            _returnOwner.setUser("User1847303185");
            fr.mom.arkeo.soap.Group _returnOwnerUserGroup = new fr.mom.arkeo.soap.Group();
            _returnOwnerUserGroup.setId("Id343446624");
            _returnOwnerUserGroup.setName("Name900271559");
            _returnOwner.setUserGroup(_returnOwnerUserGroup);
            _return.setOwner(_returnOwner);
            _return.setQualifier("Qualifier-1171848443");
            java.util.List<fr.mom.arkeo.soap.ArkQualifier> _returnQualifiers = new java.util.ArrayList<fr.mom.arkeo.soap.ArkQualifier>();
            fr.mom.arkeo.soap.ArkQualifier _returnQualifiersVal1 = new fr.mom.arkeo.soap.ArkQualifier();
            _returnQualifiersVal1.setQualifier("Qualifier-126734175");
            _returnQualifiersVal1.setUrlTarget("UrlTarget1559762198");
            _returnQualifiers.add(_returnQualifiersVal1);
            _return.getQualifiers().addAll(_returnQualifiers);
            _return.setRedirect(true);
            _return.setSaved(true);
            _return.setSubject("Subject53136879");
            _return.setTitle("Title-955191577");
            _return.setType("Type401494271");
            _return.setUrlTarget("UrlTarget-1602662300");
            _return.setUserArkId(-1957278402);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
