
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package fr.mom.arkeo.soap;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2014-09-12T12:03:33.938+02:00
 * Generated source version: 3.0.0-milestone2
 * 
 */

@javax.jws.WebService(
                      serviceName = "ArkManagerService",
                      portName = "ArkManagerPort",
                      targetNamespace = "http://soap.arkeo.mom.fr/",
                      wsdlLocation = "http://ark.mom.fr/arkeo/services/ArkManagerPort?wsdl",
                      endpointInterface = "fr.mom.arkeo.soap.ArkManager")
                      
public class ArkManagerPortImpl implements ArkManager {

    private static final Logger LOG = Logger.getLogger(ArkManagerPortImpl.class.getName());

    public fr.mom.arkeo.soap.Ark getArk(fr.mom.arkeo.soap.Account arg0,java.lang.String arg1) { 
        LOG.info("Executing operation getArk");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            fr.mom.arkeo.soap.Ark _return = new fr.mom.arkeo.soap.Ark();
            _return.setArk("Ark-1430527511");
            _return.setCreator("Creator-1319542933");
            _return.setDate("Date1011858708");
            java.util.List<fr.mom.arkeo.soap.DcElement> _returnDcElements = new java.util.ArrayList<fr.mom.arkeo.soap.DcElement>();
            fr.mom.arkeo.soap.DcElement _returnDcElementsVal1 = new fr.mom.arkeo.soap.DcElement();
            _returnDcElementsVal1.setLanguage("Language65195363");
            _returnDcElementsVal1.setName("Name1662769940");
            _returnDcElementsVal1.setValue("Value-834990445");
            _returnDcElements.add(_returnDcElementsVal1);
            _return.getDcElements().addAll(_returnDcElements);
            _return.setDescription("Description1365212708");
            _return.setLanguage("Language-670942312");
            _return.setLinkup(false);
            _return.setNaan("Naan77645651");
            _return.setName("Name-592796870");
            fr.mom.arkeo.soap.User _returnOwner = new fr.mom.arkeo.soap.User();
            _returnOwner.setDbId(-77186404);
            _returnOwner.setFirstname("Firstname1680804850");
            _returnOwner.setLastname("Lastname-547000712");
            _returnOwner.setMail("Mail1503411730");
            _returnOwner.setUid("Uid-1831193025");
            _returnOwner.setUser("User1292348547");
            fr.mom.arkeo.soap.Group _returnOwnerUserGroup = new fr.mom.arkeo.soap.Group();
            _returnOwnerUserGroup.setId("Id1999493770");
            _returnOwnerUserGroup.setName("Name271904493");
            _returnOwner.setUserGroup(_returnOwnerUserGroup);
            _return.setOwner(_returnOwner);
            _return.setQualifier("Qualifier1277617912");
            _return.setRedirect(true);
            _return.setSaved(true);
            _return.setSubject("Subject85630645");
            _return.setTitle("Title-2026837184");
            _return.setType("Type73437257");
            _return.setUrlTarget("UrlTarget170839190");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

	/* (non-Javadoc)
     * @see fr.mom.arkeo.soap.ArkManager#createArk(fr.mom.arkeo.soap.Account  arg0 ,)fr.mom.arkeo.soap.Ark  arg1 )*
     */
    public fr.mom.arkeo.soap.Ark createArk(fr.mom.arkeo.soap.Account arg0,fr.mom.arkeo.soap.Ark arg1) { 
        LOG.info("Executing operation createArk");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            fr.mom.arkeo.soap.Ark _return = new fr.mom.arkeo.soap.Ark();
            _return.setArk("Ark2004465687");
            _return.setCreator("Creator269166400");
            _return.setDate("Date-791690699");
            java.util.List<fr.mom.arkeo.soap.DcElement> _returnDcElements = new java.util.ArrayList<fr.mom.arkeo.soap.DcElement>();
            fr.mom.arkeo.soap.DcElement _returnDcElementsVal1 = new fr.mom.arkeo.soap.DcElement();
            _returnDcElementsVal1.setLanguage("Language-1849712732");
            _returnDcElementsVal1.setName("Name1578449280");
            _returnDcElementsVal1.setValue("Value750242313");
            _returnDcElements.add(_returnDcElementsVal1);
            _return.getDcElements().addAll(_returnDcElements);
            _return.setDescription("Description891382149");
            _return.setLanguage("Language-676990017");
            _return.setLinkup(true);
            _return.setNaan("Naan768359171");
            _return.setName("Name137331");
            fr.mom.arkeo.soap.User _returnOwner = new fr.mom.arkeo.soap.User();
            _returnOwner.setDbId(-1971452124);
            _returnOwner.setFirstname("Firstname106464981");
            _returnOwner.setLastname("Lastname-1030225546");
            _returnOwner.setMail("Mail1810641151");
            _returnOwner.setUid("Uid385519885");
            _returnOwner.setUser("User541792700");
            fr.mom.arkeo.soap.Group _returnOwnerUserGroup = new fr.mom.arkeo.soap.Group();
            _returnOwnerUserGroup.setId("Id-754450799");
            _returnOwnerUserGroup.setName("Name1401010645");
            _returnOwner.setUserGroup(_returnOwnerUserGroup);
            _return.setOwner(_returnOwner);
            _return.setQualifier("Qualifier1762876079");
            _return.setRedirect(true);
            _return.setSaved(true);
            _return.setSubject("Subject455399087");
            _return.setTitle("Title306862547");
            _return.setType("Type-929563896");
            _return.setUrlTarget("UrlTarget23800602");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see fr.mom.arkeo.soap.ArkManager#updateArk(fr.mom.arkeo.soap.Account  arg0 ,)fr.mom.arkeo.soap.Ark  arg1 )*
     */
    public fr.mom.arkeo.soap.Ark updateArk(fr.mom.arkeo.soap.Account arg0,fr.mom.arkeo.soap.Ark arg1) { 
        LOG.info("Executing operation updateArk");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            fr.mom.arkeo.soap.Ark _return = new fr.mom.arkeo.soap.Ark();
            _return.setArk("Ark-168500489");
            _return.setCreator("Creator-695246683");
            _return.setDate("Date1099555309");
            java.util.List<fr.mom.arkeo.soap.DcElement> _returnDcElements = new java.util.ArrayList<fr.mom.arkeo.soap.DcElement>();
            fr.mom.arkeo.soap.DcElement _returnDcElementsVal1 = new fr.mom.arkeo.soap.DcElement();
            _returnDcElementsVal1.setLanguage("Language1906305493");
            _returnDcElementsVal1.setName("Name934285999");
            _returnDcElementsVal1.setValue("Value1242461899");
            _returnDcElements.add(_returnDcElementsVal1);
            _return.getDcElements().addAll(_returnDcElements);
            _return.setDescription("Description661852293");
            _return.setLanguage("Language-262490881");
            _return.setLinkup(false);
            _return.setNaan("Naan2053255097");
            _return.setName("Name-1161339806");
            fr.mom.arkeo.soap.User _returnOwner = new fr.mom.arkeo.soap.User();
            _returnOwner.setDbId(-32241620);
            _returnOwner.setFirstname("Firstname1968420993");
            _returnOwner.setLastname("Lastname-1151036861");
            _returnOwner.setMail("Mail433003263");
            _returnOwner.setUid("Uid189038167");
            _returnOwner.setUser("User2078499090");
            fr.mom.arkeo.soap.Group _returnOwnerUserGroup = new fr.mom.arkeo.soap.Group();
            _returnOwnerUserGroup.setId("Id1617847667");
            _returnOwnerUserGroup.setName("Name-1424928763");
            _returnOwner.setUserGroup(_returnOwnerUserGroup);
            _return.setOwner(_returnOwner);
            _return.setQualifier("Qualifier-874799922");
            _return.setRedirect(false);
            _return.setSaved(false);
            _return.setSubject("Subject624688073");
            _return.setTitle("Title627300717");
            _return.setType("Type-241147148");
            _return.setUrlTarget("UrlTarget-776229714");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
