
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package fr.mom.arkeo.soap;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2014-09-12T11:25:11.020+02:00
 * Generated source version: 3.0.0-milestone2
 * 
 */

@javax.jws.WebService(
                      serviceName = "LoginService",
                      portName = "LoginPort",
                      targetNamespace = "http://soap.arkeo.mom.fr/",
                      wsdlLocation = "http://ark.mom.fr/arkeo/services/login?wsdl",
                      endpointInterface = "fr.mom.arkeo.soap.Login")
                      
public class LoginPortImpl implements Login {

    private static final Logger LOG = Logger.getLogger(LoginPortImpl.class.getName());

    /* (non-Javadoc)
     * @see fr.mom.arkeo.soap.Login#authentification(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 )*
     */
    public fr.mom.arkeo.soap.Account authentification(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2) { 
        LOG.info("Executing operation authentification");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            fr.mom.arkeo.soap.Account _return = new fr.mom.arkeo.soap.Account();
            _return.setBaseId("BaseId-1397732554");
            java.util.List<fr.mom.arkeo.soap.Group> _returnGroups = new java.util.ArrayList<fr.mom.arkeo.soap.Group>();
            fr.mom.arkeo.soap.Group _returnGroupsVal1 = new fr.mom.arkeo.soap.Group();
            _returnGroupsVal1.setId("Id1593714560");
            _returnGroupsVal1.setName("Name-900975298");
            _returnGroups.add(_returnGroupsVal1);
            _return.getGroups().addAll(_returnGroups);
            fr.mom.arkeo.soap.User _returnUser = new fr.mom.arkeo.soap.User();
            _returnUser.setDbId(-277116202);
            _returnUser.setFirstname("Firstname1356462039");
            _returnUser.setLastname("Lastname887861674");
            _returnUser.setMail("Mail-1110245529");
            _returnUser.setUid("Uid-845358231");
            _returnUser.setUser("User-1154361348");
            fr.mom.arkeo.soap.Group _returnUserUserGroup = new fr.mom.arkeo.soap.Group();
            _returnUserUserGroup.setId("Id1911733689");
            _returnUserUserGroup.setName("Name754924928");
            _returnUser.setUserGroup(_returnUserUserGroup);
            _return.setUser(_returnUser);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
