package fr.mom.arkeo.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2014-09-12T11:25:11.035+02:00
 * Generated source version: 3.0.0-milestone2
 * 
 */
@WebService(targetNamespace = "http://soap.arkeo.mom.fr/", name = "Login")
@XmlSeeAlso({ObjectFactory.class})
public interface Login {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "authentification", targetNamespace = "http://soap.arkeo.mom.fr/", className = "fr.mom.arkeo.soap.Authentification")
    @WebMethod
    @ResponseWrapper(localName = "authentificationResponse", targetNamespace = "http://soap.arkeo.mom.fr/", className = "fr.mom.arkeo.soap.AuthentificationResponse")
    public fr.mom.arkeo.soap.Account authentification(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );
}
