package fr.mom.arkeo.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2014-09-12T11:25:11.044+02:00
 * Generated source version: 3.0.0-milestone2
 * 
 */
@WebServiceClient(name = "LoginService", 
                  wsdlLocation = "http://ark.mom.fr/arkeo/services/login?wsdl",
                  targetNamespace = "http://soap.arkeo.mom.fr/") 
public class LoginService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.arkeo.mom.fr/", "LoginService");
    public final static QName LoginPort = new QName("http://soap.arkeo.mom.fr/", "LoginPort");
    static {
        URL url = null;
        try {
            url = new URL("http://ark.mom.fr/arkeo/services/login?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LoginService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://ark.mom.fr/arkeo/services/login?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LoginService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LoginService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoginService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns Login
     */
    @WebEndpoint(name = "LoginPort")
    public Login getLoginPort() {
        return super.getPort(LoginPort, Login.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Login
     */
    @WebEndpoint(name = "LoginPort")
    public Login getLoginPort(WebServiceFeature... features) {
        return super.getPort(LoginPort, Login.class, features);
    }

}
